version = 1
SPDX-PackageName = "Slang"
SPDX-PackageSupplier = "The Khronos Group, Inc."
SPDX-PackageDownloadLocation = "https://github.com/shader-slang/slang"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2016, Carnegie Mellon University and NVIDIA Corporation", "2024 The Khronos Group, Inc."]
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"

[[annotations]]
path = "docs/_includes/anchor_headings.html"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Vladimir \"allejo\" Jimenez"
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"

[[annotations]]
path = ["external/spirv/spirv.h", "external/glext.h", "external/wglext.h", "external/spirv-tools-generated/OpenCLDebugInfo100.h", "external/spirv-tools-generated/DebugInfo.h", "external/spirv-tools-generated/NonSemanticShaderDebugInfo100.h", "external/glslang-generated/glslang/build_info.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The Khronos Group, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "tests/fcpw/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Rohan Sawhney"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "external/renderdoc_app.h"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2021 Baldur Karlsson"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "external/dxc/dxcapi.h"
precedence = "aggregate"
SPDX-FileCopyrightText = "Microsoft Corporation. All rights reserved."
SPDX-License-Identifier = "LicenseRef-UOI-NCSA"

[[annotations]]
path = "source/core/slang-crypto.cpp"
precedence = "aggregate"
SPDX-FileCopyrightText = "2001 Alexander Peslyak"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The Khronos Group, Inc."
SPDX-License-Identifier = "CC-BY-4.0"
