name: Linux Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['debug', 'release']
        compiler: ['gcc', 'clang']
        platform: ['x64'] 
    steps:
    - uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        repository: "shader-slang/swiftshader"
        fileName: "vk_swiftshader_linux_${{matrix.platform}}.zip"
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: build
      run: |
        CC=${{matrix.compiler}}
        CONFIGURATION=${{matrix.configuration}}
        ARCH=${{matrix.platform}}
        TARGETARCH=${{matrix.platform}}
        if [[ "$CC" == "clang" ]]; then
          CFLAGS=-Werror
          CPPFLAGS=-Werror
          CXXFLAGS=-Werror
        fi
        source ./github_build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: slang-build-${{matrix.configuration}}-${{matrix.platform}}-${{matrix.compiler}}
        path: |
          slang.h
          slang-com-helper.h
          slang-com-ptr.h
          slang-tag-version.h
          slang-gfx.h
          prelude/*.h
          bin/**/*.dll
          bin/**/*.exe
          bin/**/*.so
          bin/**/slangc
          bin/**/slangd
          docs/*.md
    - name: test
      run: 
        CONFIGURATION=${{matrix.configuration}}
        CC=${{matrix.compiler}}
        ARCH=${{matrix.platform}}
        source ./github_test.sh