# This is a basic workflow to help you get started with Actions

name: Windows Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        platform: ['Win32', 'x64']
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: premake
      run:
        .\premake.bat vs2017 --enable-embed-stdlib=true --arch=${{matrix.platform}} --deps=true
    - name: build
      run:
        MSBuild.exe slang.sln -v:m -m -property:Configuration=${{matrix.configuration}} -property:Platform=${{matrix.platform}} -property:WindowsTargetPlatformVersion=10.0.19041.0
    - uses: actions/upload-artifact@v3
      with:
        name: slang-build-${{matrix.configuration}}-${{matrix.platform}}-${{matrix.compiler}}
        path: |
          bin/**/*.dll
          bin/**/*.exe
          bin/**/*.so
          bin/**/slangc
          bin/**/slangd
    - name: test
      run: |
        if ("${{matrix.configuration}}" -eq "Debug") {
          $testCategory = "smoke";
        }
        elseif("${{matrix.platform}}" -eq "x64") {
          $testCategory = "full";
        }
        else {
          $testCategory = "quick";
        }
        if ("${{matrix.platform}}" -eq "Win32") {
          $testPlatform = "x86";
        }
        else {
          $testPlatform = "x64";
        }
        $slangTestBinDir = ".\bin\windows-$testPlatform\${{matrix.configuration}}\";
        $env:Path += ";$slangTestBinDir";
        Invoke-WebRequest -uri "https://github.com/shader-slang/swiftshader/releases/download/v1.0/vk_swiftshader_windows_$testPlatform.zip" -Method "GET"  -Outfile "swiftshader.zip";
        Expand-Archive "swiftshader.zip" -DestinationPath $slangTestBinDir;
        & "$slangTestBinDir\slang-test.exe" -api all-dx12 -appveyor -bindir "$slangTestBinDir\" -platform $testPlatform -configuration ${{matrix.configuration}} -category $testCategory 2>&1;
    