# This is a basic workflow to help you get started with Actions

name: Windows-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        platform: ['Win32', 'x64']
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: premake
      run:
        .\premake.bat vs2017 --enable-embed-stdlib=true
    - name: build
      run:
        MSBuild.exe slang.sln -v:m -m -property:Configuration=${{matrix.configuration}} -property:Platform=${{matrix.platform}} -property:WindowsTargetPlatformVersion=10.0.19041.0
    - name: test
      run: |
        if ("${{matrix.configuration}}" -eq "Debug") {
          $testCategory = "smoke";
        }
        elseif("${{matrix.platform}}" -eq "x64") {
          $testCategory = "full";
        }
        else {
          $testCategory = "quick";
        }
        if ("${{matrix.platform}}" -eq "Win32") {
          $testPlatform = "x86";
        }
        else {
          $testPlatform = "x64";
        }
        $slangTestBinDir = ".\bin\windows-$testPlatform\${{matrix.configuration}}\";
        $env:Path += ";$slangTestBinDir";
        & "$slangTestBinDir\slang-test.exe" -api all-dx12 -appveyor -bindir "$slangTestBinDir\" -platform $testPlatform -configuration ${{matrix.configuration}} -category $testCategory;